# Generated by Django 4.0.3 on 2022-04-06 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Duracion', models.CharField(max_length=30)),
                ('Genero', models.CharField(max_length=30)),
                ('Ritmo', models.CharField(max_length=30)),
                ('Dificultad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_usuario', models.CharField(max_length=50)),
                ('Pais', models.CharField(max_length=30)),
                ('Fecha_nacimiento', models.CharField(max_length=30)),
                ('Contraseña', models.CharField(max_length=30)),
                ('Correo', models.CharField(max_length=30)),
                ('Apellido_materno', models.CharField(max_length=30)),
                ('Apellido_paterno', models.CharField(max_length=30)),
                ('Genero', models.CharField(max_length=30)),
                ('Telefono', models.CharField(max_length=30)),
                ('Foto', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_usuario', models.CharField(max_length=50)),
                ('Puntos_por_partida', models.CharField(max_length=30)),
                ('Fecha_del_juego', models.CharField(max_length=30)),
                ('Tiempo_jugado', models.CharField(max_length=30)),
                ('ID_Canciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS.canciones')),
                ('ID_Usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS.usuarios')),
            ],
        ),
    ]
