# Generated by Django 4.0.3 on 2022-04-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PAS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Correo',
        ),
    ]
