# Generated by Django 4.0.3 on 2022-04-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PAS', '0002_remove_usuarios_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Contraseña',
        ),
    ]
