# Generated by Django 4.0.3 on 2022-04-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS', '0004_usuarios_nombre_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='Numero_usuario',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
