# Generated by Django 4.0.3 on 2022-04-16 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PAS', '0005_usuarios_numero_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Apellido_materno',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='Apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='Fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='Foto',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='Genero',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='Telefono',
        ),
    ]
