# Generated by Django 4.0.3 on 2022-04-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS', '0007_remove_usuarios_numero_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='Contraseña',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
